#!/usr/bin/env python
import sys
import argparse

try:
    import awscli.clidriver
except ImportError:
    print "Couldn't import awscli: pip install awscli"
    sys.exit(0)


# arguments/commands are used for completions
# children is used for further indexing of subcommands.
INDEX = {'aws': {'arguments': [], 'commands': [], 'children': {}}}


def index_command(index_dict, help_command):
    for arg in help_command.arg_table:
        index_dict['arguments'].append('--%s' % arg)
    for cmd in help_command.command_table:
        index_dict['commands'].append(cmd)
        # Each sub command will trigger a recurse.
        child = {'arguments': [], 'commands': [], 'children': {}}
        index_dict['children'][cmd] = child
        sub_command = help_command.command_table[cmd]
        sub_help_command = sub_command.create_help_command()
        index_command(child, sub_help_command)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-o', '--output', default='completions.idx',
                        help='The filename of the index file.')
    args = parser.parse_args()
    driver = awscli.clidriver.create_clidriver()
    help_command = driver.create_help_command()
    current = INDEX['aws']
    index_command(current, help_command)

    import pprint
    result = pprint.pformat(INDEX)
    with open(args.output, 'w') as f:
        f.write(result)


main()
